# RuboCop configuration for Customer Service
# https://docs.rubocop.org/rubocop/configuration

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/migrate/**"
    - "node_modules/**"
    - "vendor/**"
    - "tmp/**"
    - "storage/**"
    - "config.ru"

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

# Rails
Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/Output:
  Exclude:
    - "db/seeds.rb"

# RSpec
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 8
  Exclude:
    - "spec/integration/**/*"

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - "spec/routing/**/*"
    - "spec/requests/**/*"
    - "spec/integration/**/*"
    - "spec/consumers/**/*"

Metrics/AbcSize:
  Exclude:
    - "app/services/orders/apply_order_created.rb"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "app/consumers/order_created_consumer.rb"
