# RuboCop configuration for Order Service (modern Rails standards)
# Run via: docker compose exec order_service bundle exec rubocop
# https://docs.rubocop.org/rubocop/configuration

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/migrate/**"
    - "node_modules/**"
    - "vendor/**"
    - "tmp/**"
    - "storage/**"
    - "config.ru"

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

# Rails (modern)
Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Rails/EnvironmentVariableAccess:
  Enabled: false

# RSpec
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - "spec/routing/**/*"
    - "spec/requests/**/*"
